language: node_js
service:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'drop database if exists propertyprolite_db;' -U postgres
  - psql -c 'create database propertyprolite_db;' -U postgres
node_js:
- 'stable'
cache:
  directories:
    - "node_modules"
notifications:
  email: false
after_success: npm run coverage
