language: node_js
service:
  - postgresql
node_js:
- 'stable'
cache:
  directories:
    - "node_modules"
notifications:
  email: false
before_script:
  - psql -c 'drop database if exists travis_ci_test;' -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
after_success: npm run coverage

